<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-07T02:55:03 IST" name="Suite1" finished-at="2025-05-07T02:55:18 IST" duration-ms="14870">
    <groups>
    </groups>
    <test started-at="2025-05-07T02:55:03 IST" name="FirstRun" finished-at="2025-05-07T02:55:18 IST" duration-ms="14870">
      <class name="com.hybridframework.testcases.login.LoginTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:03 IST" name="setUp" finished-at="2025-05-07T02:55:07 IST" duration-ms="3223" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initializePageObjects()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:07 IST" name="initializePageObjects" finished-at="2025-05-07T02:55:07 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePageObjects -->
        <test-method signature="verifyLoginWithValidCredential(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:07 IST" name="verifyLoginWithValidCredential" data-provider="loginData" finished-at="2025-05-07T02:55:08 IST" duration-ms="1523" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[krishav@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:08 IST" name="tearDown" finished-at="2025-05-07T02:55:08 IST" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:08 IST" name="setUp" finished-at="2025-05-07T02:55:10 IST" duration-ms="1507" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initializePageObjects()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:10 IST" name="initializePageObjects" finished-at="2025-05-07T02:55:10 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePageObjects -->
        <test-method signature="verifyLoginWithValidCredential(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:10 IST" name="verifyLoginWithValidCredential" data-provider="loginData" finished-at="2025-05-07T02:55:11 IST" duration-ms="1101" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[krishav134@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[454]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failure]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:16)
at com.hybridframework.testcases.login.LoginTest.verifyLoginWithValidCredential(LoginTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: Matched:Test Passes expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:14)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:11 IST" name="tearDown" finished-at="2025-05-07T02:55:11 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:11 IST" name="setUp" finished-at="2025-05-07T02:55:13 IST" duration-ms="1614" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initializePageObjects()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:13 IST" name="initializePageObjects" finished-at="2025-05-07T02:55:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePageObjects -->
        <test-method signature="verifyLoginWithValidCredential(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:13 IST" name="verifyLoginWithValidCredential" data-provider="loginData" finished-at="2025-05-07T02:55:14 IST" duration-ms="1250" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[krishav2324@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3343]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failure]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:16)
at com.hybridframework.testcases.login.LoginTest.verifyLoginWithValidCredential(LoginTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: Matched:Test Passes expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:14)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:14 IST" name="tearDown" finished-at="2025-05-07T02:55:14 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:14 IST" name="setUp" finished-at="2025-05-07T02:55:17 IST" duration-ms="2151" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initializePageObjects()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:17 IST" name="initializePageObjects" finished-at="2025-05-07T02:55:17 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePageObjects -->
        <test-method signature="verifyLoginWithInvalidCredential()[pri:2, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:17 IST" name="verifyLoginWithInvalidCredential" finished-at="2025-05-07T02:55:18 IST" duration-ms="999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:18 IST" name="tearDown" finished-at="2025-05-07T02:55:18 IST" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="cleanupData()[pri:0, instance:com.hybridframework.testcases.login.LoginTest@13518f37]" started-at="2025-05-07T02:55:18 IST" name="cleanupData" finished-at="2025-05-07T02:55:18 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanupData -->
      </class> <!-- com.hybridframework.testcases.login.LoginTest -->
    </test> <!-- FirstRun -->
  </suite> <!-- Suite1 -->
</testng-results>
